(function($){$.fn.trackAction=function(args){this.each(function(i){track_action(this,args);});}
function track_action(el,args){if(el.getAttribute('data-track-event')=='set')
return;args=push_defaults(el,args);$(el).on(args['event'],function(e){if(typeof _gaq!="undefined"){_gaq.push(['_trackEvent',args['category'],args['action'],args['label']]);}});el.setAttribute('data-track-event','set');}
function push_defaults(el,args)
{if(typeof args==='undefined')args={};var atts=['event','category','action','label'];for(i in atts)
{if(typeof args[atts[i]]=='undefined')
{var tag='data-track-'+atts[i];args[atts[i]]=el.getAttribute(tag);}}
return args;}
$(function($){var gravity_forms=$('.gform_wrapper form');if(gravity_forms.length)
gravity_forms.each(function(i){var form_id=this.id.split('_')[1];track_action(this,{event:'submit',category:'Contact Form',action:'Form Submission',label:'Gravity Form '+form_id});});var track_objs=$('[data-track-event]');if(track_objs.length)
track_objs.each(function(i){track_action(this);});});})(jQuery);;jQuery(document).ready(function($){$('#editLeft, #editRight').remove();if(getCookie('demoBar')!='false'){$('#pbhs-demo-bar').find('.selectOptions > li').each(function(){$(this).click(function(){$(this).parent().toggle();window.location.href="http://"+window.location.host+window.location.pathname+'?'+$(this).attr('rel');});});$('.selectBox > span').click(function(){$(this).siblings('ul').toggle();});$('#defaults').click(function(){window.location.href="http://"+window.location.host+window.location.pathname+'?reset=true';})}
$('#demoTab').click(function(){var position=$(this).parent().position();if(!$(this).parent().is(':animated')&&position.left<0){$(this).parent().animate({left:'0'},300);}else if(!$(this).parent().is(':animated')){$(this).parent().animate({left:'-211'},300);}});$.address.change(function(event){var resetOption=decodeURI((RegExp('reset'+'='+'(.+?)(&|$)').exec(location.search)||[,null])[1]);if(resetOption!='true'){if(typeof(demoTheme)!="undefined"){var theme=getCookie('theme');if(theme!=demoTheme){setCookie('theme',demoTheme,365);}}
if(typeof(demoColor)!="undefined"){var colorOptions=getCookie('color');if(colorOptions!=demoColor){setCookie('color',demoColor,365);}}
if(typeof(demoPhotoOption)!="undefined"){var photoOptions=getCookie('photoOption');if(photoOptions!=demoPhotoOption){setCookie('photoOption',demoPhotoOption,365);}}
if(typeof(demo_c_colorOne)!="undefined"){var c_colorOne=getCookie('c_colorOne');if(c_colorOne!=demo_c_colorOne){setCookie('c_colorOne',demo_c_colorOne,365);}}
if(typeof(demo_c_colorTwo)!="undefined"){var c_colorTwo=getCookie('c_colorTwo');if(c_colorTwo!=demo_c_colorTwo){setCookie('c_colorTwo',demo_c_colorTwo,365);}}}});});function setCookie(c_name,value,exdays){var exdate=new Date();exdate.setDate(exdate.getDate()+exdays);var c_value=escape(value)+((exdays==null)?"; path=/":"; expires="+exdate.toUTCString()+"; path=/");document.cookie=c_name+"="+c_value;}
function getCookie(c_name){var i,x,y,ARRcookies=document.cookie.split(";");for(i=0;i<ARRcookies.length;i++){x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);x=x.replace(/^\s+|\s+$/g,"");if(x==c_name){return unescape(y);}}};(function($){$.address=(function(){var _trigger=function(name){$($.address).trigger($.extend($.Event(name),(function(){var parameters={},parameterNames=$.address.parameterNames();for(var i=0,l=parameterNames.length;i<l;i++){parameters[parameterNames[i]]=$.address.parameter(parameterNames[i]);}
return{value:$.address.value(),path:$.address.path(),pathNames:$.address.pathNames(),parameterNames:parameterNames,parameters:parameters,queryString:$.address.queryString()};}).call($.address)));},_array=function(obj){return Array.prototype.slice.call(obj);},_bind=function(value,data,fn){$().bind.apply($($.address),Array.prototype.slice.call(arguments));return $.address;},_supportsState=function(){return(_h.pushState&&_opts.state!==UNDEFINED);},_hrefState=function(){return('/'+_l.pathname.replace(new RegExp(_opts.state),'')+
_l.search+(_hrefHash()?'#'+_hrefHash():'')).replace(_re,'/');},_hrefHash=function(){var index=_l.href.indexOf('#');return index!=-1?_crawl(_l.href.substr(index+1),FALSE):'';},_href=function(){return _supportsState()?_hrefState():_hrefHash();},_window=function(){try{return top.document!==UNDEFINED?top:window;}catch(e){return window;}},_js=function(){return'javascript';},_strict=function(value){value=value.toString();return(_opts.strict&&value.substr(0,1)!='/'?'/':'')+value;},_crawl=function(value,direction){if(_opts.crawlable&&direction){return(value!==''?'!':'')+value;}
return value.replace(/^\!/,'');},_cssint=function(el,value){return parseInt(el.css(value),10);},_listen=function(){if(!_silent){var hash=_href(),diff=_value!=hash;if(diff){if(_msie&&_version<7){_l.reload();}else{if(_msie&&!_hashchange&&_opts.history){_st(_html,50);}
_value=hash;_update(FALSE);}}}},_update=function(internal){_trigger(CHANGE);_trigger(internal?INTERNAL_CHANGE:EXTERNAL_CHANGE);_st(_track,10);},_track=function(){if(_opts.tracker!=='null'&&_opts.tracker!==null){var fn=$.isFunction(_opts.tracker)?_opts.tracker:_t[_opts.tracker],value=(_l.pathname+_l.search+
($.address&&!_supportsState()?$.address.value():'')).replace(/\/\//,'/').replace(/^\/$/,'');if($.isFunction(fn)){fn(value);}else if($.isFunction(_t.urchinTracker)){_t.urchinTracker(value);}else if(_t.pageTracker!==UNDEFINED&&$.isFunction(_t.pageTracker._trackPageview)){_t.pageTracker._trackPageview(value);}else if(_t._gaq!==UNDEFINED&&$.isFunction(_t._gaq.push)){_t._gaq.push(['_trackPageview',decodeURI(value)]);}}},_html=function(){var src=_js()+':'+FALSE+';document.open();document.writeln(\'<html><head><title>'+
_d.title.replace(/\'/g,'\\\'')+'</title><script>var '+ID+' = "'+_href()+
(_d.domain!=_l.hostname?'";document.domain="'+_d.domain:'')+'";</'+'script></head></html>\');document.close();';if(_version<7){_frame.src=src;}else{_frame.contentWindow.location.replace(src);}},_options=function(){if(_url&&_qi!=-1){var i,param,params=_url.substr(_qi+1).split('&');for(i=0;i<params.length;i++){param=params[i].split('=');if(/^(autoUpdate|crawlable|history|strict|wrap)$/.test(param[0])){_opts[param[0]]=(isNaN(param[1])?/^(true|yes)$/i.test(param[1]):(parseInt(param[1],10)!==0));}
if(/^(state|tracker)$/.test(param[0])){_opts[param[0]]=param[1];}}
_url=null;}
_value=_href();},_load=function(){if(!_loaded){_loaded=TRUE;_options();var complete=function(){_enable.call(this);_unescape.call(this);},body=$('body').ajaxComplete(complete);complete();if(_opts.wrap){var wrap=$('body > *').wrapAll('<div style="padding:'+
(_cssint(body,'marginTop')+_cssint(body,'paddingTop'))+'px '+
(_cssint(body,'marginRight')+_cssint(body,'paddingRight'))+'px '+
(_cssint(body,'marginBottom')+_cssint(body,'paddingBottom'))+'px '+
(_cssint(body,'marginLeft')+_cssint(body,'paddingLeft'))+'px;" />').parent().wrap('<div id="'+ID+'" style="height:100%;overflow:auto;position:relative;'+
(_webkit&&!window.statusbar.visible?'resize:both;':'')+'" />');$('html, body').css({height:'100%',margin:0,padding:0,overflow:'hidden'});if(_webkit){$('<style type="text/css" />').appendTo('head').text('#'+ID+'::-webkit-resizer { background-color: #fff; }');}}
if(_msie&&!_hashchange){var frameset=_d.getElementsByTagName('frameset')[0];_frame=_d.createElement((frameset?'':'i')+'frame');_frame.src=_js()+':'+FALSE;if(frameset){frameset.insertAdjacentElement('beforeEnd',_frame);frameset[frameset.cols?'cols':'rows']+=',0';_frame.noResize=TRUE;_frame.frameBorder=_frame.frameSpacing=0;}else{_frame.style.display='none';_frame.style.width=_frame.style.height=0;_frame.tabIndex=-1;_d.body.insertAdjacentElement('afterBegin',_frame);}
_st(function(){$(_frame).bind('load',function(){var win=_frame.contentWindow;_value=win[ID]!==UNDEFINED?win[ID]:'';if(_value!=_href()){_update(FALSE);_l.hash=_crawl(_value,TRUE);}});if(_frame.contentWindow[ID]===UNDEFINED){_html();}},50);}
_st(function(){_trigger('init');_update(FALSE);},1);if(!_supportsState()){if(_hashchange){if(_t.addEventListener){_t.addEventListener(HASH_CHANGE,_listen,FALSE);}else if(_t.attachEvent){_t.attachEvent('on'+HASH_CHANGE,_listen);}}else{_si(_listen,50);}}}},_enable=function(){var el,elements=$('a'),length=elements.size(),delay=1,index=-1,sel='[rel*="address:"]',fn=function(){if(++index!=length){el=$(elements.get(index));if(el.is(sel)){el.address(sel);}
_st(fn,delay);}};_st(fn,delay);},_popstate=function(){if(_value!=_href()){_value=_href();_update(FALSE);}},_unload=function(){if(_t.removeEventListener){_t.removeEventListener(HASH_CHANGE,_listen,FALSE);}else if(_t.detachEvent){_t.detachEvent('on'+HASH_CHANGE,_listen);}},_unescape=function(){if(_opts.crawlable){var base=_l.pathname.replace(/\/$/,''),fragment='_escaped_fragment_';if($('body').html().indexOf(fragment)!=-1){$('a[href]:not([href^=http]), a[href*="'+document.domain+'"]').each(function(){var href=$(this).attr('href').replace(/^http:/,'').replace(new RegExp(base+'/?$'),'');if(href===''||href.indexOf(fragment)!=-1){$(this).attr('href','#'+encodeURI(decodeURIComponent(href.replace(new RegExp('/(.*)\\?'+
fragment+'=(.*)$'))),'!$2'));}});}}},UNDEFINED,ID='jQueryAddress',STRING='string',HASH_CHANGE='hashchange',INIT='init',CHANGE='change',INTERNAL_CHANGE='internalChange',EXTERNAL_CHANGE='externalChange',TRUE=true,FALSE=false,_opts={autoUpdate:TRUE,crawlable:FALSE,history:TRUE,strict:TRUE,wrap:FALSE},_browser=$.browser,_version=parseFloat(_browser.version),_msie=!$.support.opacity,_webkit=_browser.webkit||_browser.safari,_t=_window(),_d=_t.document,_h=_t.history,_l=_t.location,_si=setInterval,_st=setTimeout,_re=/\/{2,9}/g,_agent=navigator.userAgent,_hashchange='on'+HASH_CHANGE in _t,_frame,_form,_url=$('script:last').attr('src'),_qi=_url?_url.indexOf('?'):-1,_title=_d.title,_silent=FALSE,_loaded=FALSE,_justset=TRUE,_juststart=TRUE,_updating=FALSE,_listeners={},_value=_href();if(_msie){_version=parseFloat(_agent.substr(_agent.indexOf('MSIE')+4));if(_d.documentMode&&_d.documentMode!=_version){_version=_d.documentMode!=8?7:8;}
var pc=_d.onpropertychange;_d.onpropertychange=function(){if(pc){pc.call(_d);}
if(_d.title!=_title&&_d.title.indexOf('#'+_href())!=-1){_d.title=_title;}};}
if(_h.navigationMode){_h.navigationMode='compatible';}
if(document.readyState=='complete'){var interval=setInterval(function(){if($.address){_load();clearInterval(interval);}},50);}else{_options();$(_load);}
$(window).bind('popstate',_popstate).bind('unload',_unload);return{bind:function(type,data,fn){return _bind.apply(this,_array(arguments));},init:function(data,fn){return _bind.apply(this,[INIT].concat(_array(arguments)));},change:function(data,fn){return _bind.apply(this,[CHANGE].concat(_array(arguments)));},internalChange:function(data,fn){return _bind.apply(this,[INTERNAL_CHANGE].concat(_array(arguments)));},externalChange:function(data,fn){return _bind.apply(this,[EXTERNAL_CHANGE].concat(_array(arguments)));},baseURL:function(){var url=_l.href;if(url.indexOf('#')!=-1){url=url.substr(0,url.indexOf('#'));}
if(/\/$/.test(url)){url=url.substr(0,url.length-1);}
return url;},autoUpdate:function(value){if(value!==UNDEFINED){_opts.autoUpdate=value;return this;}
return _opts.autoUpdate;},crawlable:function(value){if(value!==UNDEFINED){_opts.crawlable=value;return this;}
return _opts.crawlable;},history:function(value){if(value!==UNDEFINED){_opts.history=value;return this;}
return _opts.history;},state:function(value){if(value!==UNDEFINED){_opts.state=value;var hrefState=_hrefState();if(_opts.state!==UNDEFINED){if(_h.pushState){if(hrefState.substr(0,3)=='/#/'){_l.replace(_opts.state.replace(/^\/$/,'')+hrefState.substr(2));}}else if(hrefState!='/'&&hrefState.replace(/^\/#/,'')!=_hrefHash()){_st(function(){_l.replace(_opts.state.replace(/^\/$/,'')+'/#'+hrefState);},1);}}
return this;}
return _opts.state;},strict:function(value){if(value!==UNDEFINED){_opts.strict=value;return this;}
return _opts.strict;},tracker:function(value){if(value!==UNDEFINED){_opts.tracker=value;return this;}
return _opts.tracker;},wrap:function(value){if(value!==UNDEFINED){_opts.wrap=value;return this;}
return _opts.wrap;},update:function(){_updating=TRUE;this.value(_value);_updating=FALSE;return this;},title:function(value){if(value!==UNDEFINED){_st(function(){_title=_d.title=value;if(_juststart&&_frame&&_frame.contentWindow&&_frame.contentWindow.document){_frame.contentWindow.document.title=value;_juststart=FALSE;}
if(!_justset&&_browser.mozilla){_l.replace(_l.href.indexOf('#')!=-1?_l.href:_l.href+'#');}
_justset=FALSE;},50);return this;}
return _d.title;},value:function(value){if(value!==UNDEFINED){value=_strict(value);if(value=='/'){value='';}
if(_value==value&&!_updating){return;}
_justset=TRUE;_value=value;if(_opts.autoUpdate||_updating){_update(TRUE);if(_supportsState()){_h[_opts.history?'pushState':'replaceState']({},'',_opts.state.replace(/\/$/,'')+(_value===''?'/':_value));}else{_silent=TRUE;if(_webkit){if(_opts.history){_l.hash='#'+_crawl(_value,TRUE);}else{_l.replace('#'+_crawl(_value,TRUE));}}else if(_value!=_href()){if(_opts.history){_l.hash='#'+_crawl(_value,TRUE);}else{_l.replace('#'+_crawl(_value,TRUE));}}
if((_msie&&!_hashchange)&&_opts.history){_st(_html,50);}
if(_webkit){_st(function(){_silent=FALSE;},1);}else{_silent=FALSE;}}}
return this;}
return _strict(_value);},path:function(value){if(value!==UNDEFINED){var qs=this.queryString(),hash=this.hash();this.value(value+(qs?'?'+qs:'')+(hash?'#'+hash:''));return this;}
return _strict(_value).split('#')[0].split('?')[0];},pathNames:function(){var path=this.path(),names=path.replace(_re,'/').split('/');if(path.substr(0,1)=='/'||path.length===0){names.splice(0,1);}
if(path.substr(path.length-1,1)=='/'){names.splice(names.length-1,1);}
return names;},queryString:function(value){if(value!==UNDEFINED){var hash=this.hash();this.value(this.path()+(value?'?'+value:'')+(hash?'#'+hash:''));return this;}
var arr=_value.split('?');return arr.slice(1,arr.length).join('?').split('#')[0];},parameter:function(name,value,append){var i,params;if(value!==UNDEFINED){var names=this.parameterNames();params=[];value=value?value.toString():'';for(i=0;i<names.length;i++){var n=names[i],v=this.parameter(n);if(typeof v==STRING){v=[v];}
if(n==name){v=(value===null||value==='')?[]:(append?v.concat([value]):[value]);}
for(var j=0;j<v.length;j++){params.push(n+'='+v[j]);}}
if($.inArray(name,names)==-1&&value!==null&&value!==''){params.push(name+'='+value);}
this.queryString(params.join('&'));return this;}
value=this.queryString();if(value){var r=[];params=value.split('&');for(i=0;i<params.length;i++){var p=params[i].split('=');if(p[0]==name){r.push(p.slice(1).join('='));}}
if(r.length!==0){return r.length!=1?r:r[0];}}},parameterNames:function(){var qs=this.queryString(),names=[];if(qs&&qs.indexOf('=')!=-1){var params=qs.split('&');for(var i=0;i<params.length;i++){var name=params[i].split('=')[0];if($.inArray(name,names)==-1){names.push(name);}}}
return names;},hash:function(value){if(value!==UNDEFINED){this.value(_value.split('#')[0]+(value?'#'+value:''));return this;}
var arr=_value.split('#');return arr.slice(1,arr.length).join('#');}};})();$.fn.address=function(fn){var sel;if(typeof fn=='string'){sel=fn;fn=undefined;}
if(!$(this).attr('address')){var f=function(e){if(e.shiftKey||e.ctrlKey||e.metaKey||e.which==2){return true;}
if($(this).is('a')){e.preventDefault();var value=fn?fn.call(this):/address:/.test($(this).attr('rel'))?$(this).attr('rel').split('address:')[1].split(' ')[0]:$.address.state()!==undefined&&!/^\/?$/.test($.address.state())?$(this).attr('href').replace(new RegExp('^(.*'+$.address.state()+'|\\.)'),''):$(this).attr('href').replace(/^(#\!?|\.)/,'');$.address.value(value);}};$(sel?sel:this).live('click',f).live('submit',function(e){if($(this).is('form')){e.preventDefault();var action=$(this).attr('action'),value=fn?fn.call(this):(action.indexOf('?')!=-1?action.replace(/&$/,''):action+'?')+
$(this).serialize();$.address.value(value);}}).attr('address',true);}
return this;};})(jQuery);;(function($){var ColorPicker=function(){var
ids={},inAction,charMin=65,visible,tpl='<div class="colorpicker"><div class="colorpicker_color"><div><div></div></div></div><div class="colorpicker_hue"><div></div></div><div class="colorpicker_new_color"></div><div class="colorpicker_current_color"></div><div class="colorpicker_hex"><input type="text" maxlength="6" size="6" /></div><div class="colorpicker_rgb_r colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_rgb_g colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_rgb_b colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_hsb_h colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_hsb_s colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_hsb_b colorpicker_field"><input type="text" maxlength="3" size="3" /><span></span></div><div class="colorpicker_submit"></div></div>',defaults={eventName:'click',onShow:function(){},onBeforeShow:function(){},onHide:function(){},onChange:function(){},onSubmit:function(){},color:'ff0000',livePreview:true,flat:false},fillRGBFields=function(hsb,cal){var rgb=HSBToRGB(hsb);$(cal).data('colorpicker').fields.eq(1).val(rgb.r).end().eq(2).val(rgb.g).end().eq(3).val(rgb.b).end();},fillHSBFields=function(hsb,cal){$(cal).data('colorpicker').fields.eq(4).val(hsb.h).end().eq(5).val(hsb.s).end().eq(6).val(hsb.b).end();},fillHexFields=function(hsb,cal){$(cal).data('colorpicker').fields.eq(0).val(HSBToHex(hsb)).end();},setSelector=function(hsb,cal){$(cal).data('colorpicker').selector.css('backgroundColor','#'+HSBToHex({h:hsb.h,s:100,b:100}));$(cal).data('colorpicker').selectorIndic.css({left:parseInt(150*hsb.s/100,10),top:parseInt(150*(100-hsb.b)/100,10)});},setHue=function(hsb,cal){$(cal).data('colorpicker').hue.css('top',parseInt(150-150*hsb.h/360,10));},setCurrentColor=function(hsb,cal){$(cal).data('colorpicker').currentColor.css('backgroundColor','#'+HSBToHex(hsb));},setNewColor=function(hsb,cal){$(cal).data('colorpicker').newColor.css('backgroundColor','#'+HSBToHex(hsb));},keyDown=function(ev){var pressedKey=ev.charCode||ev.keyCode||-1;if((pressedKey>charMin&&pressedKey<=90)||pressedKey==32){return false;}
var cal=$(this).parent().parent();if(cal.data('colorpicker').livePreview===true){change.apply(this);}},change=function(ev){var cal=$(this).parent().parent(),col;if(this.parentNode.className.indexOf('_hex')>0){cal.data('colorpicker').color=col=HexToHSB(fixHex(this.value));}else if(this.parentNode.className.indexOf('_hsb')>0){cal.data('colorpicker').color=col=fixHSB({h:parseInt(cal.data('colorpicker').fields.eq(4).val(),10),s:parseInt(cal.data('colorpicker').fields.eq(5).val(),10),b:parseInt(cal.data('colorpicker').fields.eq(6).val(),10)});}else{cal.data('colorpicker').color=col=RGBToHSB(fixRGB({r:parseInt(cal.data('colorpicker').fields.eq(1).val(),10),g:parseInt(cal.data('colorpicker').fields.eq(2).val(),10),b:parseInt(cal.data('colorpicker').fields.eq(3).val(),10)}));}
if(ev){fillRGBFields(col,cal.get(0));fillHexFields(col,cal.get(0));fillHSBFields(col,cal.get(0));}
setSelector(col,cal.get(0));setHue(col,cal.get(0));setNewColor(col,cal.get(0));cal.data('colorpicker').onChange.apply(cal,[col,HSBToHex(col),HSBToRGB(col)]);},blur=function(ev){var cal=$(this).parent().parent();cal.data('colorpicker').fields.parent().removeClass('colorpicker_focus');},focus=function(){charMin=this.parentNode.className.indexOf('_hex')>0?70:65;$(this).parent().parent().data('colorpicker').fields.parent().removeClass('colorpicker_focus');$(this).parent().addClass('colorpicker_focus');},downIncrement=function(ev){var field=$(this).parent().find('input').focus();var current={el:$(this).parent().addClass('colorpicker_slider'),max:this.parentNode.className.indexOf('_hsb_h')>0?360:(this.parentNode.className.indexOf('_hsb')>0?100:255),y:ev.pageY,field:field,val:parseInt(field.val(),10),preview:$(this).parent().parent().data('colorpicker').livePreview};$(document).bind('mouseup',current,upIncrement);$(document).bind('mousemove',current,moveIncrement);},moveIncrement=function(ev){ev.data.field.val(Math.max(0,Math.min(ev.data.max,parseInt(ev.data.val+ev.pageY-ev.data.y,10))));if(ev.data.preview){change.apply(ev.data.field.get(0),[true]);}
return false;},upIncrement=function(ev){change.apply(ev.data.field.get(0),[true]);ev.data.el.removeClass('colorpicker_slider').find('input').focus();$(document).unbind('mouseup',upIncrement);$(document).unbind('mousemove',moveIncrement);return false;},downHue=function(ev){var current={cal:$(this).parent(),y:$(this).offset().top};current.preview=current.cal.data('colorpicker').livePreview;$(document).bind('mouseup',current,upHue);$(document).bind('mousemove',current,moveHue);},moveHue=function(ev){change.apply(ev.data.cal.data('colorpicker').fields.eq(4).val(parseInt(360*(150-Math.max(0,Math.min(150,(ev.pageY-ev.data.y))))/150,10)).get(0),[ev.data.preview]);return false;},upHue=function(ev){fillRGBFields(ev.data.cal.data('colorpicker').color,ev.data.cal.get(0));fillHexFields(ev.data.cal.data('colorpicker').color,ev.data.cal.get(0));$(document).unbind('mouseup',upHue);$(document).unbind('mousemove',moveHue);return false;},downSelector=function(ev){var current={cal:$(this).parent(),pos:$(this).offset()};current.preview=current.cal.data('colorpicker').livePreview;$(document).bind('mouseup',current,upSelector);$(document).bind('mousemove',current,moveSelector);},moveSelector=function(ev){change.apply(ev.data.cal.data('colorpicker').fields.eq(6).val(parseInt(100*(150-Math.max(0,Math.min(150,(ev.pageY-ev.data.pos.top))))/150,10)).end().eq(5).val(parseInt(100*(Math.max(0,Math.min(150,(ev.pageX-ev.data.pos.left))))/150,10)).get(0),[ev.data.preview]);return false;},upSelector=function(ev){fillRGBFields(ev.data.cal.data('colorpicker').color,ev.data.cal.get(0));fillHexFields(ev.data.cal.data('colorpicker').color,ev.data.cal.get(0));$(document).unbind('mouseup',upSelector);$(document).unbind('mousemove',moveSelector);return false;},enterSubmit=function(ev){$(this).addClass('colorpicker_focus');},leaveSubmit=function(ev){$(this).removeClass('colorpicker_focus');},clickSubmit=function(ev){var cal=$(this).parent();var col=cal.data('colorpicker').color;cal.data('colorpicker').origColor=col;setCurrentColor(col,cal.get(0));cal.data('colorpicker').onSubmit(col,HSBToHex(col),HSBToRGB(col),cal.data('colorpicker').el);},show=function(ev){var cal=$('#'+$(this).data('colorpickerId'));cal.data('colorpicker').onBeforeShow.apply(this,[cal.get(0)]);var pos=$(this).offset();var viewPort=getViewport();var top=pos.top+this.offsetHeight;var left=pos.left;if(top+176>viewPort.t+viewPort.h){top-=this.offsetHeight+176;}
if(left+356>viewPort.l+viewPort.w){left-=356;}
cal.css({left:left+'px',top:top+'px'});if(cal.data('colorpicker').onShow.apply(this,[cal.get(0)])!=false){cal.show();}
$(document).bind('mousedown',{cal:cal},hide);return false;},hide=function(ev){if(!isChildOf(ev.data.cal.get(0),ev.target,ev.data.cal.get(0))){if(ev.data.cal.data('colorpicker').onHide.apply(this,[ev.data.cal.get(0)])!=false){ev.data.cal.hide();}
$(document).unbind('mousedown',hide);}},isChildOf=function(parentEl,el,container){if(parentEl==el){return true;}
if(parentEl.contains){return parentEl.contains(el);}
if(parentEl.compareDocumentPosition){return!!(parentEl.compareDocumentPosition(el)&16);}
var prEl=el.parentNode;while(prEl&&prEl!=container){if(prEl==parentEl)
return true;prEl=prEl.parentNode;}
return false;},getViewport=function(){var m=document.compatMode=='CSS1Compat';return{l:window.pageXOffset||(m?document.documentElement.scrollLeft:document.body.scrollLeft),t:window.pageYOffset||(m?document.documentElement.scrollTop:document.body.scrollTop),w:window.innerWidth||(m?document.documentElement.clientWidth:document.body.clientWidth),h:window.innerHeight||(m?document.documentElement.clientHeight:document.body.clientHeight)};},fixHSB=function(hsb){return{h:Math.min(360,Math.max(0,hsb.h)),s:Math.min(100,Math.max(0,hsb.s)),b:Math.min(100,Math.max(0,hsb.b))};},fixRGB=function(rgb){return{r:Math.min(255,Math.max(0,rgb.r)),g:Math.min(255,Math.max(0,rgb.g)),b:Math.min(255,Math.max(0,rgb.b))};},fixHex=function(hex){var len=6-hex.length;if(len>0){var o=[];for(var i=0;i<len;i++){o.push('0');}
o.push(hex);hex=o.join('');}
return hex;},HexToRGB=function(hex){var hex=parseInt(((hex.indexOf('#')>-1)?hex.substring(1):hex),16);return{r:hex>>16,g:(hex&0x00FF00)>>8,b:(hex&0x0000FF)};},HexToHSB=function(hex){return RGBToHSB(HexToRGB(hex));},RGBToHSB=function(rgb){var hsb={h:0,s:0,b:0};var min=Math.min(rgb.r,rgb.g,rgb.b);var max=Math.max(rgb.r,rgb.g,rgb.b);var delta=max-min;hsb.b=max;if(max!=0){}
hsb.s=max!=0?255*delta/max:0;if(hsb.s!=0){if(rgb.r==max){hsb.h=(rgb.g-rgb.b)/delta;}else if(rgb.g==max){hsb.h=2+(rgb.b-rgb.r)/delta;}else{hsb.h=4+(rgb.r-rgb.g)/delta;}}else{hsb.h=-1;}
hsb.h*=60;if(hsb.h<0){hsb.h+=360;}
hsb.s*=100/255;hsb.b*=100/255;return hsb;},HSBToRGB=function(hsb){var rgb={};var h=Math.round(hsb.h);var s=Math.round(hsb.s*255/100);var v=Math.round(hsb.b*255/100);if(s==0){rgb.r=rgb.g=rgb.b=v;}else{var t1=v;var t2=(255-s)*v/255;var t3=(t1-t2)*(h%60)/60;if(h==360)h=0;if(h<60){rgb.r=t1;rgb.b=t2;rgb.g=t2+t3}
else if(h<120){rgb.g=t1;rgb.b=t2;rgb.r=t1-t3}
else if(h<180){rgb.g=t1;rgb.r=t2;rgb.b=t2+t3}
else if(h<240){rgb.b=t1;rgb.r=t2;rgb.g=t1-t3}
else if(h<300){rgb.b=t1;rgb.g=t2;rgb.r=t2+t3}
else if(h<360){rgb.r=t1;rgb.g=t2;rgb.b=t1-t3}
else{rgb.r=0;rgb.g=0;rgb.b=0}}
return{r:Math.round(rgb.r),g:Math.round(rgb.g),b:Math.round(rgb.b)};},RGBToHex=function(rgb){var hex=[rgb.r.toString(16),rgb.g.toString(16),rgb.b.toString(16)];$.each(hex,function(nr,val){if(val.length==1){hex[nr]='0'+val;}});return hex.join('');},HSBToHex=function(hsb){return RGBToHex(HSBToRGB(hsb));},restoreOriginal=function(){var cal=$(this).parent();var col=cal.data('colorpicker').origColor;cal.data('colorpicker').color=col;fillRGBFields(col,cal.get(0));fillHexFields(col,cal.get(0));fillHSBFields(col,cal.get(0));setSelector(col,cal.get(0));setHue(col,cal.get(0));setNewColor(col,cal.get(0));};return{init:function(opt){opt=$.extend({},defaults,opt||{});if(typeof opt.color=='string'){opt.color=HexToHSB(opt.color);}else if(opt.color.r!=undefined&&opt.color.g!=undefined&&opt.color.b!=undefined){opt.color=RGBToHSB(opt.color);}else if(opt.color.h!=undefined&&opt.color.s!=undefined&&opt.color.b!=undefined){opt.color=fixHSB(opt.color);}else{return this;}
return this.each(function(){if(!$(this).data('colorpickerId')){var options=$.extend({},opt);options.origColor=opt.color;var id='collorpicker_'+parseInt(Math.random()*1000);$(this).data('colorpickerId',id);var cal=$(tpl).attr('id',id);if(options.flat){cal.appendTo(this).show();}else{cal.appendTo(document.body);}
options.fields=cal.find('input').bind('keyup',keyDown).bind('change',change).bind('blur',blur).bind('focus',focus);cal.find('span').bind('mousedown',downIncrement).end().find('>div.colorpicker_current_color').bind('click',restoreOriginal);options.selector=cal.find('div.colorpicker_color').bind('mousedown',downSelector);options.selectorIndic=options.selector.find('div div');options.el=this;options.hue=cal.find('div.colorpicker_hue div');cal.find('div.colorpicker_hue').bind('mousedown',downHue);options.newColor=cal.find('div.colorpicker_new_color');options.currentColor=cal.find('div.colorpicker_current_color');cal.data('colorpicker',options);cal.find('div.colorpicker_submit').bind('mouseenter',enterSubmit).bind('mouseleave',leaveSubmit).bind('click',clickSubmit);fillRGBFields(options.color,cal.get(0));fillHSBFields(options.color,cal.get(0));fillHexFields(options.color,cal.get(0));setHue(options.color,cal.get(0));setSelector(options.color,cal.get(0));setCurrentColor(options.color,cal.get(0));setNewColor(options.color,cal.get(0));if(options.flat){cal.css({position:'relative',display:'block'});}else{$(this).bind(options.eventName,show);}}});},showPicker:function(){return this.each(function(){if($(this).data('colorpickerId')){show.apply(this);}});},hidePicker:function(){return this.each(function(){if($(this).data('colorpickerId')){$('#'+$(this).data('colorpickerId')).hide();}});},setColor:function(col){if(typeof col=='string'){col=HexToHSB(col);}else if(col.r!=undefined&&col.g!=undefined&&col.b!=undefined){col=RGBToHSB(col);}else if(col.h!=undefined&&col.s!=undefined&&col.b!=undefined){col=fixHSB(col);}else{return this;}
return this.each(function(){if($(this).data('colorpickerId')){var cal=$('#'+$(this).data('colorpickerId'));cal.data('colorpicker').color=col;cal.data('colorpicker').origColor=col;fillRGBFields(col,cal.get(0));fillHSBFields(col,cal.get(0));fillHexFields(col,cal.get(0));setHue(col,cal.get(0));setSelector(col,cal.get(0));setCurrentColor(col,cal.get(0));setNewColor(col,cal.get(0));}});}};}();$.fn.extend({ColorPicker:ColorPicker.init,ColorPickerHide:ColorPicker.hidePicker,ColorPickerShow:ColorPicker.showPicker,ColorPickerSetColor:ColorPicker.setColor});})(jQuery);(function($){var EYE=window.EYE=function(){var _registered={init:[]};return{init:function(){$.each(_registered.init,function(nr,fn){fn.call();});},extend:function(prop){for(var i in prop){if(prop[i]!=undefined){this[i]=prop[i];}}},register:function(fn,type){if(!_registered[type]){_registered[type]=[];}
_registered[type].push(fn);}};}();$(EYE.init);})(jQuery);;(function($){EYE.extend({getPosition:function(e,forceIt)
{var x=0;var y=0;var es=e.style;var restoreStyles=false;if(forceIt&&jQuery.curCSS(e,'display')=='none'){var oldVisibility=es.visibility;var oldPosition=es.position;restoreStyles=true;es.visibility='hidden';es.display='block';es.position='absolute';}
var el=e;if(el.getBoundingClientRect){var box=el.getBoundingClientRect();x=box.left+Math.max(document.documentElement.scrollLeft,document.body.scrollLeft)-2;y=box.top+Math.max(document.documentElement.scrollTop,document.body.scrollTop)-2;}else{x=el.offsetLeft;y=el.offsetTop;el=el.offsetParent;if(e!=el){while(el){x+=el.offsetLeft;y+=el.offsetTop;el=el.offsetParent;}}
if(jQuery.browser.safari&&jQuery.curCSS(e,'position')=='absolute'){x-=document.body.offsetLeft;y-=document.body.offsetTop;}
el=e.parentNode;while(el&&el.tagName.toUpperCase()!='BODY'&&el.tagName.toUpperCase()!='HTML')
{if(jQuery.curCSS(el,'display')!='inline'){x-=el.scrollLeft;y-=el.scrollTop;}
el=el.parentNode;}}
if(restoreStyles==true){es.display='none';es.position=oldPosition;es.visibility=oldVisibility;}
return{x:x,y:y};},getSize:function(e)
{var w=parseInt(jQuery.curCSS(e,'width'),10);var h=parseInt(jQuery.curCSS(e,'height'),10);var wb=0;var hb=0;if(jQuery.curCSS(e,'display')!='none'){wb=e.offsetWidth;hb=e.offsetHeight;}else{var es=e.style;var oldVisibility=es.visibility;var oldPosition=es.position;es.visibility='hidden';es.display='block';es.position='absolute';wb=e.offsetWidth;hb=e.offsetHeight;es.display='none';es.position=oldPosition;es.visibility=oldVisibility;}
return{w:w,h:h,wb:wb,hb:hb};},getClient:function(e)
{var h,w;if(e){w=e.clientWidth;h=e.clientHeight;}else{var de=document.documentElement;w=window.innerWidth||self.innerWidth||(de&&de.clientWidth)||document.body.clientWidth;h=window.innerHeight||self.innerHeight||(de&&de.clientHeight)||document.body.clientHeight;}
return{w:w,h:h};},getScroll:function(e)
{var t=0,l=0,w=0,h=0,iw=0,ih=0;if(e&&e.nodeName.toLowerCase()!='body'){t=e.scrollTop;l=e.scrollLeft;w=e.scrollWidth;h=e.scrollHeight;}else{if(document.documentElement){t=document.documentElement.scrollTop;l=document.documentElement.scrollLeft;w=document.documentElement.scrollWidth;h=document.documentElement.scrollHeight;}else if(document.body){t=document.body.scrollTop;l=document.body.scrollLeft;w=document.body.scrollWidth;h=document.body.scrollHeight;}
if(typeof pageYOffset!='undefined'){t=pageYOffset;l=pageXOffset;}
iw=self.innerWidth||document.documentElement.clientWidth||document.body.clientWidth||0;ih=self.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0;}
return{t:t,l:l,w:w,h:h,iw:iw,ih:ih};},getMargins:function(e,toInteger)
{var t=jQuery.curCSS(e,'marginTop')||'';var r=jQuery.curCSS(e,'marginRight')||'';var b=jQuery.curCSS(e,'marginBottom')||'';var l=jQuery.curCSS(e,'marginLeft')||'';if(toInteger)
return{t:parseInt(t,10)||0,r:parseInt(r,10)||0,b:parseInt(b,10)||0,l:parseInt(l,10)};else
return{t:t,r:r,b:b,l:l};},getPadding:function(e,toInteger)
{var t=jQuery.curCSS(e,'paddingTop')||'';var r=jQuery.curCSS(e,'paddingRight')||'';var b=jQuery.curCSS(e,'paddingBottom')||'';var l=jQuery.curCSS(e,'paddingLeft')||'';if(toInteger)
return{t:parseInt(t,10)||0,r:parseInt(r,10)||0,b:parseInt(b,10)||0,l:parseInt(l,10)};else
return{t:t,r:r,b:b,l:l};},getBorder:function(e,toInteger)
{var t=jQuery.curCSS(e,'borderTopWidth')||'';var r=jQuery.curCSS(e,'borderRightWidth')||'';var b=jQuery.curCSS(e,'borderBottomWidth')||'';var l=jQuery.curCSS(e,'borderLeftWidth')||'';if(toInteger)
return{t:parseInt(t,10)||0,r:parseInt(r,10)||0,b:parseInt(b,10)||0,l:parseInt(l,10)||0};else
return{t:t,r:r,b:b,l:l};},traverseDOM:function(nodeEl,func)
{func(nodeEl);nodeEl=nodeEl.firstChild;while(nodeEl){EYE.traverseDOM(nodeEl,func);nodeEl=nodeEl.nextSibling;}},getInnerWidth:function(el,scroll){var offsetW=el.offsetWidth;return scroll?Math.max(el.scrollWidth,offsetW)-offsetW+el.clientWidth:el.clientWidth;},getInnerHeight:function(el,scroll){var offsetH=el.offsetHeight;return scroll?Math.max(el.scrollHeight,offsetH)-offsetH+el.clientHeight:el.clientHeight;},getExtraWidth:function(el){if($.boxModel)
return(parseInt($.curCSS(el,'paddingLeft'))||0)
+(parseInt($.curCSS(el,'paddingRight'))||0)
+(parseInt($.curCSS(el,'borderLeftWidth'))||0)
+(parseInt($.curCSS(el,'borderRightWidth'))||0);return 0;},getExtraHeight:function(el){if($.boxModel)
return(parseInt($.curCSS(el,'paddingTop'))||0)
+(parseInt($.curCSS(el,'paddingBottom'))||0)
+(parseInt($.curCSS(el,'borderTopWidth'))||0)
+(parseInt($.curCSS(el,'borderBottomWidth'))||0);return 0;},isChildOf:function(parentEl,el,container){if(parentEl==el){return true;}
if(!el||!el.nodeType||el.nodeType!=1){return false;}
if(parentEl.contains&&!$.browser.safari){return parentEl.contains(el);}
if(parentEl.compareDocumentPosition){return!!(parentEl.compareDocumentPosition(el)&16);}
var prEl=el.parentNode;while(prEl&&prEl!=container){if(prEl==parentEl)
return true;prEl=prEl.parentNode;}
return false;},centerEl:function(el,axis)
{var clientScroll=EYE.getScroll();var size=EYE.getSize(el);if(!axis||axis=='vertically')
$(el).css({top:clientScroll.t+((Math.min(clientScroll.h,clientScroll.ih)-size.hb)/2)+'px'});if(!axis||axis=='horizontally')
$(el).css({left:clientScroll.l+((Math.min(clientScroll.w,clientScroll.iw)-size.wb)/2)+'px'});}});if(!$.easing.easeout){$.easing.easeout=function(p,n,firstNum,delta,duration){return-delta*((n=n/duration-1)*n*n*n-1)+firstNum;};}})(jQuery);;(function($){var initLayout=function(){var hash=window.location.hash.replace('#','');var currentTab=$('ul.navigationTabs a').bind('click',showTab).filter('a[rel='+hash+']');if(currentTab.size()==0){currentTab=$('ul.navigationTabs a:first');}
showTab.apply(currentTab.get(0));$('#colorpickerHolder').ColorPicker({flat:true});$('.colorpickerHolder2').each(function(){var picker=$(this);var startVals=jQuery.parseJSON(picker.siblings('input').val().replace(/'/g,'"'));picker.ColorPicker({color:'#'+startVals.HEX,flat:true,onSubmit:GetNewColors});});$('.colorpickerHolder2 > div').css('position','absolute');var widt=false;$('.colorSelector2').bind('click',function(){$(this).siblings('.colorpickerHolder2').stop().animate({height:widt?0:173},500);widt=!widt;});$('#colorSelector').ColorPicker({color:'#0000ff',onShow:function(colpkr){$(colpkr).fadeIn(500);return false;},onHide:function(colpkr){$(colpkr).fadeOut(500);return false;},onChange:function(hsb,hex,rgb){$('#colorSelector div').css('backgroundColor','#'+hex);}});};var showTab=function(e){var tabIndex=$('ul.navigationTabs a').removeClass('active').index(this);$(this).addClass('active').blur();$('div.tab').hide().eq(tabIndex).show();};EYE.register(initLayout,'init');})(jQuery);GetNewColors=function(hsb,hex,rgb,el){$(el).siblings('.colorSelector2').children('div').css('backgroundColor','#'+hex);var input=$(el).siblings('input');var colorOptions=$.parseJSON(input.attr('value').replace(/'/g,'"'));if(!colorOptions.defaultColor){colorOptions.defaultColor=colorOptions.HEX;}else if(hex==colorOptions.defaultColor){colorOptions.defaultColor=false;}
colorOptions.useDefaults=false;var hsb2=hsb;if(colorOptions.maxHSB!=undefined){hsb2=setMaxOuts(colorOptions.maxHSB,hsb2);}
if(colorOptions.minHSB!=undefined){hsb2=setMinOuts(colorOptions.minHSB,hsb2);}
colorOptions.HEX=hex;colorOptions.RGB=RGBarrayToString(rgb);colorOptions.HEX2=HSBToHex(hsb2);for(v in colorOptions.variants){if(colorOptions.variants[v].compare==undefined){var compare=HexToHSB(colorOptions.defaultColor);compare.tempHSB=hsb}else{var compare=HexToHSB(colorOptions.variants[colorOptions.variants[v].compare].defaultColor);compare.HEX=colorOptions.variants[colorOptions.variants[v].compare].HEX;compare.tempHSB=HexToHSB(compare.HEX)}
var thisHSB={}
if(colorOptions.variants[v].defaultColor=='BlackOrWhite'){if(compare.tempHSB.b<68||compare.tempHSB.s>75)thisHSB=HexToHSB('FFFFFF');else thisHSB=HexToHSB('000000');}else{var thisDefaultHSB=HexToHSB(colorOptions.variants[v].defaultColor);var HSB_Diff={'h':thisDefaultHSB.h-compare.h,'s':thisDefaultHSB.s-compare.s,'b':thisDefaultHSB.b-compare.b}
thisHSB.h=compare.tempHSB.h+HSB_Diff.h;thisHSB.s=compare.tempHSB.s+HSB_Diff.s;thisHSB.b=compare.tempHSB.b+HSB_Diff.b;}
for(part in thisDefaultHSB){switch(part){case'h':if(thisHSB.h>359){thisHSB.h-=359}
if(thisHSB.h<0){thisHSB.h+=359}
break;case's':if(thisHSB.s>100){thisHSB.s=100}
if(thisHSB.s<0){thisHSB.s=0}
break;case'b':if(thisHSB.b>100){thisHSB.b-=100;}
if(thisHSB.b<0){thisHSB.b+=100;}
break;}}
if(colorOptions.variants[v].maxHSB!=undefined){thisHSB=setMaxOuts(colorOptions.variants[v].maxHSB,thisHSB);}
if(colorOptions.variants[v].minHSB!=undefined){thisHSB=setMinOuts(colorOptions.variants[v].minHSB,thisHSB);}
colorOptions.variants[v].HEX=HSBToHex(thisHSB);colorOptions.variants[v].RGB=RGBarrayToString(HSBToRGB(thisHSB));}
var name=input.attr('name').split('.');window.location.href="http://"+window.location.host+window.location.pathname+'?'+name[1]+'='+JSON.stringify(colorOptions);$(el).stop().animate({height:0},500);}
setMaxOuts=function(maxHSB,currentHSB){for(part in maxHSB){switch(part){case'h':if(maxHSB.h!=0&&currentHSB.h>maxHSB.h){currentHSB.h=maxHSB.h}
break;case's':if(maxHSB.s!=0&&currentHSB.s>maxHSB.s){currentHSB.s=maxHSB.s}
break;case'b':if(maxHSB.b!=0&&currentHSB.b>maxHSB.b){currentHSB.b=maxHSB.b}
break;}}
return currentHSB;}
setMinOuts=function(minHSB,currentHSB){for(part in minHSB){switch(part){case'h':if(minHSB.h!=360&&currentHSB.h<minHSB.h){currentHSB.h=minHSB.h}
break;case's':if(minHSB.s!=100&&currentHSB.s<minHSB.s){currentHSB.s=minHSB.s}
break;case'b':if(minHSB.b!=100&&currentHSB.b<minHSB.b){currentHSB.b=minHSB.b}
break;}}
return currentHSB;}
RGBarrayToString=function(rgb){var output='';for(color in rgb){if(color=='b'){output+=rgb[color]}else{output+=rgb[color]+','}}
return output;}
HexToRGB=function(hex){var hex=parseInt(((hex.indexOf('#')>-1)?hex.substring(1):hex),16);return{r:hex>>16,g:(hex&0x00FF00)>>8,b:(hex&0x0000FF)};}
HexToHSB=function(hex){var rgb=HexToRGB(hex);return RGBToHSB(rgb);}
HSBToHex=function(hsb){return RGBToHex(HSBToRGB(hsb));}
RGBToHex=function(rgb){var hex=[rgb.r.toString(16),rgb.g.toString(16),rgb.b.toString(16)];$.each(hex,function(nr,val){if(val.length==1){hex[nr]='0'+val;}});return hex.join('');}
HSBToRGB=function(hsb){var rgb={};var h=Math.round(hsb.h);var s=Math.round(hsb.s*255/100);var v=Math.round(hsb.b*255/100);if(s==0){rgb.r=rgb.g=rgb.b=v;}else{var t1=v;var t2=(255-s)*v/255;var t3=(t1-t2)*(h%60)/60;if(h==360)h=0;if(h<60){rgb.r=t1;rgb.b=t2;rgb.g=t2+t3}
else if(h<120){rgb.g=t1;rgb.b=t2;rgb.r=t1-t3}
else if(h<180){rgb.g=t1;rgb.r=t2;rgb.b=t2+t3}
else if(h<240){rgb.b=t1;rgb.r=t2;rgb.g=t1-t3}
else if(h<300){rgb.b=t1;rgb.g=t2;rgb.r=t2+t3}
else if(h<360){rgb.r=t1;rgb.g=t2;rgb.b=t1-t3}
else{rgb.r=0;rgb.g=0;rgb.b=0}}
return{r:Math.round(rgb.r),g:Math.round(rgb.g),b:Math.round(rgb.b)};}
RGBToHSB=function(rgb){var hsb={h:0,s:0,b:0};var min=Math.min(rgb.r,rgb.g,rgb.b);var max=Math.max(rgb.r,rgb.g,rgb.b);var delta=max-min;hsb.b=max;if(max!=0){}
hsb.s=max!=0?255*delta/max:0;if(hsb.s!=0){if(rgb.r==max){hsb.h=(rgb.g-rgb.b)/delta;}else if(rgb.g==max){hsb.h=2+(rgb.b-rgb.r)/delta;}else{hsb.h=4+(rgb.r-rgb.g)/delta;}}else{hsb.h=-1;}
hsb.h*=60;if(hsb.h<0){hsb.h+=360;}
hsb.s*=100/255;hsb.b*=100/255;return hsb;}